### ISSUE TITLE
Wayland videodriver uses lower color depth

### ISSUE THREAD

**Issue by voidanix** [blue-nebula/base#131]
**First seen in**: current master

**Observation**: switching the SDL_VIDEODRIVER to wayland causes the game to use a lower color depth, this is mostly noticed by the "clipping" of the gradients' color

![20200718142833](https://user-images.githubusercontent.com/51296985/87852638-3630d700-c8f3-11ea-9846-b6b39e1fb17c.png)

**How to reproduce**:
1. launch the game with `SDL_VIDEODRIVER=wayland` on wayland

I searched the issue list and checked that this is not a duplicate :white_check_mark: 
I tried to rename my *config.cfg*, and the problem also occurs with default settings :white_check_mark:

**Comment by TheAssassin** [comment]
What distro (version) have you tested this on?

Do you happen to know how to solve this? Does it work if you use XWayland?

**Comment by voidanix** [comment]
Sorry for the late reply.

Distro is Fedora rawhide with GNOME 3.38; I haven't been able to fix it but the colors do appear normal when using XWayland.

**Comment by voidanix** [comment]
This has fixed itself with distro upgrades so it must have been an SDL2/DE issue, closing
