### ISSUE TITLE
Can't play Red Eclipse demos

### ISSUE THREAD

**Issue by robalni** [blue-nebula/base#158]
I think that as long as the game is compatible with Red Eclipse it would be nice if you could play Red Eclipse demos. Currently when I try that I get the message "sorry, demos/demoname.dmo is not a demo file".

This happens because the game requires the demo magic value to be "BLUE_NEBULA_DEMO" but Red Eclipse demos have magic value "RED_ECLIPSE_DEMO". This value is defined in game/game.h:8

```
#define VERSION_DEMOMAGIC "BLUE_NEBULA_DEMO"
```

**Comment by MoonPadUSer** [comment]
hum that's a very good point but I'd like to have @TheAssassin opinion on that just to be sure
