### ISSUE TITLE
non english versions

### ISSUE THREAD

**Issue by bmorel** [blue-nebula/base#164]
game is, AFAIK only available to people understanding english and it's damn acronyms like AFAIK (as far as I know).

I can not see any technical reason to not use translatable strings when possible, especially in new commits.

**Comment by MoonPadUSer** [comment]
how would that look like?

**Comment by bmorel** [comment]
It's mostly about selecting a tool, and applying some call over all translatable strings. Like gettext.

**Comment by TheAssassin** [comment]
Duplicate of #56.
