### ISSUE TITLE
regression: serverbrowser icons are buggy

### ISSUE THREAD

**Issue by bmorel** [blue-nebula/base#18]
in commit af74d03b5e4a79a61157b0f402e23c97e610f5e2 the map thumbnails are all identical when trying to switch server while already playing (and match currently played map's thumbnail).

Reported by varco on irc.

**Comment by voidanix** [comment]
Could confirm, also when firing up the game all map thumbnails don't show up (only the logo is shown)

**Comment by MoonPadUSer** [comment]
@voidanix that's normal, they usually take a little longer to load. Or do you mean they won't load at all?

**Comment by TheAssassin** [comment]
@MoonPadUSer in your PR, everything seems to be fixed. In the current master, I cannot see the previews. It only shows the RE logo, which is the "fallback" displayed if no preview is available.

**Comment by MoonPadUSer** [comment]
since my PR has been merged, imma go ahead and close this
