### ISSUE TITLE
 seperating /teamkillban with 2 new vars: /botteamkillban and /playerteamkillban

### ISSUE THREAD

**Issue by Lagetta** [blue-nebula/base#186]
There is a command called `teamkillban` that gives warnings before person is banned from the server. I think that this command should be seperated to players and bots. There are some servers like openvar ones where killing alliy bots is almost inevitable with very strong weapons. While bots don't matter when they are killed, players might get really annoyed by it (myself included). You kill no matter a bot or a player, only that it is an ally, you could still get a ban which is kinda stupid.

**Comment by MoonPadUSer** [comment]
I suggest using `/playerteamkillban` instead of `/playerkillban`

**Comment by Lagetta** [comment]
I guess this is a better command name. It speaks mostly by itself what it does.

**Comment by MoonPadUSer** [comment]
I don't think that's a viable option rn, it's something you could do in a full release since it would definitely break compatibility

**Comment by TheAssassin** [comment]
Even then it would be viable to do it now, as it's server-side-only. We use the classic RE 1.6 servers just fine right now. We don't have to block work on server-side tasks.

There's always been development servers, by the way. They will use our master server automatically, too. And gameplay wise, this doesn't really hurt anyone.
