### ISSUE TITLE
Locked game modes are not shown that are locked

### ISSUE THREAD

**Issue by Lagetta** [blue-nebula/base#199]
Some servers like duel only servers have locked modes. In the new vote interference those locked modes are not shown.
![Screenshot at 2020-08-08 17-09-12](https://user-images.githubusercontent.com/53313579/89712550-4429c300-d99a-11ea-818b-b9879dd42fb5.png)

I can click them, but it doesn't do anything at all.

Also I can select the map to vote what is shown in the list, but I need moderator status to even vote those maps. Why are they visible in the map selection in the first place? And why vote button is clickable?

**Comment by MoonPadUSer** [comment]
I'll take a look at that in the next few days, it seems like I've overlooked some things when adding the new map selector
