### ISSUE TITLE
Ctf protect interface

### ISSUE THREAD

**Issue by Lagetta** [blue-nebula/base#235]
While playing capture the flag protect mode while holding the flag, you can't clearly see how long you and the enemy are holding the flag to get a point. Even if it's shown it is not visible enough.

I am thinking if it's possible to place it in these logos, or do it like in bomber a count down.
![image](https://user-images.githubusercontent.com/53313579/126554020-4ae92784-74a8-471b-96bb-ecc1f3af3b18.png)

**Comment by TheAssassin** [comment]
Duplicate of #234.
