### ISSUE TITLE
Can I play maps made by re2?

### ISSUE THREAD

**Issue by ghost** [blue-nebula/base#238]
I created a map in red eclipse 2, can I play it in this game? If not, can I convert it to playable in this game?

**Comment by voidanix** [comment]
Nope, RE2 uses a different engine (still based on Cube 2) and is therefore incompatible.

Once it was possible to import Cube 2 maps into RE2's Tesseract engine but support for that has been removed before the final release.

I'm not aware of any methods to convert RE2 maps to make it compatible with RE 1.6.0/BN, but I doubt there are any.
