### ISSUE TITLE
Logo for Blue Nebula

### ISSUE THREAD

**Issue by TheAssassin** [blue-nebula/base#34]
We need a new logo, as discussed in #25.

@SalatielSauer made a proposal, see https://github.com/blue-nebula/base/issues/25#issuecomment-636401556. Even if it might just be used temporarily, it doesn't look bad at all. The main criticism I have it's not a vector graphic, which would be better in the long term. Something in SVG that also looks good in grayscale resp. with some clear contours which could also work in high-contrast situations.

To be able to use @SalatielSauer's logo e.g., as a base, we need to clarify licensing. @SalatielSauer what license is your logo published under? Would something like the CC By(-SA) 4.0 Intl. work for you? We need one that grants us and everyone else the right to also modify it and create derivatived works.

**Comment by SalatielSauer** [comment]
I won't be able to make a svg version available, but CC BY-SA 4.0 sounds good to me.
As I said before, the "Nebula" font is free for non-commercial use, so I included versions of the banner without it... Good luck with the project :)

**Comment by TheAssassin** [comment]
I agree to @Lyberta that a free (as in speech) font would be better. I am also not a big fan of the look. The emblem itself is okay, though, so I personally consider it a good logo even if just temporary. May I ask how you created it?

**Comment by SalatielSauer** [comment]
I created it using GIMP 2.10, you can download the source file (.xcf) [here](https://github.com/SalatielSauer/misc/raw/master/bluenebula.xcf).

**Comment by MoonPadUSer** [comment]
@SalatielSauer that looks so incredibly awesome!

**Comment by MoonPadUSer** [comment]
@SalatielSauer @TheAssassin I took the logo and implemented it into the game, here are a few showcases how that could look like (pls ignore the crappy attempt of mine to make logo in the upper right)
![Blue-Nebula-Showcase 1](https://user-images.githubusercontent.com/37220464/83542848-d2e21580-a4fb-11ea-86ee-b50d643f4711.png)
![Blue-Nebula-Showcase 2](https://user-images.githubusercontent.com/37220464/83542851-d5446f80-a4fb-11ea-894d-7285260f8182.png)

**Comment by TheAssassin** [comment]
Please ignore the Cube 2 logo. We can either remove it (I think we aren't obliged to have it there), or move it downwards.

Other than that, I have a few fonts in mind that I want to try out. The logo itself will do for now, thanks again @SalatielSauer. I want to embed it in an SVG nevertheless, and will try to come up with a unique lettering that can stand for itself, too, if it has to.

**Comment by TheAssassin** [comment]
I took @MoonPadUSer's proposal and created some SVG versions (with non-italic fonts). SVG allows for easily changing the font (position, face, color, ...), and allows for easily making versions for dark and light backgrounds, etc.

![logo1 svg](https://user-images.githubusercontent.com/4503202/86420220-264fab00-bcd6-11ea-9712-f20dcd5ad309.png)
![logo2 svg](https://user-images.githubusercontent.com/4503202/86420222-2780d800-bcd6-11ea-83cb-c5caaecc5ec6.png)

Slightly different font size. I think we should go no higher than the sizer in the first one, and no lower than in the second proposal.

Please let me know what you think! I'll put all the logo files on GitHub soon-ish. Thanks again @SalatielSauer for helping out.

**Comment by shacknetisp** [comment]
The design looks fine to me. Comparing these two, I like the first better as not using extra vertical space.

It'll be nice to get the logo into the game, some maps look a little weird without it on their signs :)

**Comment by TheAssassin** [comment]
@shacknetisp I like the first one more, too. I've centered the font as good as possible. This issue has indeed been open for too long, we really need to close this issue.

**Comment by MoonPadUSer** [comment]
I like the first one too

**Comment by TheAssassin** [comment]
I'll implement the first one now, to finally resolve this issue. Thanks everyone for their help and input!
