### ISSUE TITLE
Alt + Backspace in the Console to delete entire words

### ISSUE THREAD

**Issue by MoonPadUSer** [blue-nebula/base#54]
The title should describe it pretty well I think. #58

**Comment by TheAssassin** [comment]
I think `alt` and `backspace` is more of a "standard", isn't it? At least in most consoles I have ever tried, it works like that.

**Comment by MoonPadUSer** [comment]
hum, I mean ... that works too ofc.

**Comment by MoonPadUSer** [comment]
I made a PR: https://github.com/blue-nebula/base/pull/58

**Comment by TheAssassin** [comment]
Please don't close issues before the respective PR has been merged. Use `Closes #58` in the PR description, then it's closed automatically.

**Comment by MoonPadUSer** [comment]
oh
