### ISSUE TITLE
Improve @ mentions 

### ISSUE THREAD

**Issue by Lagetta** [blue-nebula/base#83]
Instead of pain white text when mentioning someone's nickname, I think it would be nice that player mention gets it's own colour and a badge (that small symbol next to the nickname).

**Comment by TheAssassin** [comment]
Badge refers to the player "role" icon, i.e., what's displayed in front of the nicks in the console, scoreboard etc.

**Comment by MoonPadUSer** [comment]
that should be easily pssible inside the code, instead of replacing it with `game::players[i]->name` I can just say `game::colourname(game::players[i])` and in theory that should do it

**Comment by MoonPadUSer** [comment]
done

**Comment by MoonPadUSer** [comment]
I'll close the issue since the PR is merged
